name: Deploy Labmda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install libraries
        run: |
            cd function
            ls
            pwd
            python -m pip install --upgrade pip
            if [ -f requirements.txt]; then pip install -r requirements.txt -t .; fi
      - name: create zip bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip . 
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with: 
          name: zipped-bundle
      - name: Display structure of downloaded files
        run: ls -R
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload to S3
        run: aws s3 cp ${{ github.sha }}.zip s3://test-sz-20240909/${{ github.repository }}/${{ github.sha }}.zip
  
  deploy:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY }}
          aws-region: us-east-1
      - name: update function code
        run: |
            aws lambda update-function-code \
              --function-name Github_Function \
              --s3-bucket test-sz-20240909 \
              --s3-key ${{ github.repository }}/${{ github.sha }}.zip \
              --publish
